  server:
    port: 8081
  spring:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
    application:
      name: travelnote
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/travelnote?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 123456
    redis:
      host: 127.0.0.1
      port: 6379

      lettuce:
        pool:
          max-active: 30
          max-idle: 15
          min-idle: 5
          time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null
  mybatis-plus:
    type-aliases-package: com.localshop.travelnote.entity
  logging:
    level:
      com.localshop.travelnote: debug
